- name: Bandit
  baseMaxHitPoints: 50
  baseGloryValue: 30
  baseDefence: 30
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - iron-sword
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: Fabric
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayNameId: Bandit
    animationSetName: bandit

- name: Lizardman
  baseMaxHitPoints: 50
  baseGloryValue: 40
  baseDefence: 30
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - punch
    - bite
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: CarrotSeed
      quantity: 4
    - itemName: PineLogs
      quantity: 2
    - itemName: Greencap
  clientConfig:
    extendsClassName: Mob
    displayNameId: Lizardman
    animationSetName: lizardman

- name: LizardmanGuard
  baseMaxHitPoints: 80
  baseGloryValue: 60
  baseDefence: 50
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 2
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - iron-spear
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: CarrotSeed
      quantity: 4
    - itemName: IronOre
  clientConfig:
    extendsClassName: Mob
    displayNameId: Lizardman guard
    animationSetName: lizardman-guard

- name: Orc
  baseMaxHitPoints: 80
  baseGloryValue: 50
  baseDefence: 30
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  spawnGroundTypes:
    - Snow
  spawnCategory: mobs
  actions:
    - punch
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: CarrotSeed
      quantity: 4
    - itemName: Redcap
  clientConfig:
    extendsClassName: Mob
    displayNameId: Orc
    animationSetName: orc

- name: OrcBerserker
  baseMaxHitPoints: 80
  baseGloryValue: 70
  baseDefence: 50
  baseMoveRate: 600
  baseWanderRate: 10000
  baseAttackRange: 2
  viewRange: 8
  spawnGroundTypes:
    - Snow
  spawnCategory: mobs
  actions:
    - iron-sword
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: CarrotSeed
      quantity: 4
    - itemName: IronOre
  clientConfig:
    extendsClassName: Mob
    displayNameId: Orc berserker
    animationSetName: orc-berserker

- name: Cow
  baseMaxHitPoints: 50
  baseGloryValue: 15
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - punch
    - bite
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: RawMeat
      dropRate: 100
      quantity: 2
  clientConfig:
    extendsClassName: Mob
    displayNameId: Cow
    animationSetName: adult-cow

- name: FruitBat
  baseMaxHitPoints: 50
  baseGloryValue: 15
  baseMoveRate: 500
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - bite
  dropList:
    - itemName: Bones
      dropRate: 100
    - itemName: Redcap
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayNameId: Fruit bat
    animationSetName: fruit-bat

- name: Snake
  baseMaxHitPoints: 40
  baseGloryValue: 20
  baseMoveRate: 400
  baseWanderRate: 10000
  baseAttackRange: 2
  viewRange: 8
  spawnGroundTypes:
    - Grass
  spawnCategory: mobs
  actions:
    - bite
    - spit-venom
  dropList:
    - itemName: Greencap
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayNameId: Snake
    animationSetName: snake

- name: FireElemental
  baseMaxHitPoints: 60
  baseGloryValue: 40
  baseMoveRate: 600
  baseWanderRate: 10000
  baseAttackRange: 3
  viewRange: 8
  craftingStationClass: Furnace
  spawnGroundTypes:
    - Lava
  spawnCategory: mobs
  actions:
    - fireball
  dropList:
    - itemName: FireGem
      dropRate: 100
  clientConfig:
    extendsClassName: Mob
    displayNameId: Fire elemental
    animationSetName: fire-elemental

- name: PineTree
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  categories:
    - Tree
  spawnGroundTypes:
    - Grass
    - Snow
  spawnCategory: trees
  dropList:
    - itemName: PineLogs
      dropRate: 100
      quantity: 4
  clientConfig:
    displayNameId: Pine tree
    showDisplayNameOnHover: false
    animationSetName: pine-tree
    animationFrameSequence: [1]

- name: IronRocks
  highBlocking: true
  baseMaxHitPoints: 200
  baseGloryValue: 20
  categories:
    - OreRock
  spawnGroundTypes:
    - Grass
    - Snow
  spawnCategory: oreRocks
  dropList:
    - itemName: IronOre
      dropRate: 100
      quantity: 4
  clientConfig:
    displayNameId: Iron ore
    showDisplayNameOnHover: false
    animationSetName: iron-rocks
    animationFrameSequence: [1]

- name: CarrotSeedling
  code: SGEJ4470
  baseMaxHitPoints: 20
  baseGloryValue: 5
  transformationEntityType: CarrotPlant
  transformationTimer: 600000
  categories:
    - Crop
  spawnGroundTypes:
    - Grass
  spawnCategory: forage
  clientConfig:
    displayNameId: Carrot seedling
    animationSetName: carrot-seedling
    animationFrameSequence: [1]

- name: CarrotPlant
  code: LMAU2310
  baseMaxHitPoints: 20
  baseGloryValue: 5
  categories:
    - Crop
  dropList:
    - itemName: Carrot
      dropRate: 100
      quantity: 2
    - itemName: Carrot
      dropRate: 20
      quantity: 1
      rolls: 3
  clientConfig:
    displayNameId: Carrots
    animationSetName: carrot-plant
    animationFrameSequence: [1]

# - name: Anvil
#   code: ZEWT6029
#   maxHitPoints: 300

# - name: WoodenChest
#   code: DUZJ6112
#   maxHitPoints: 250
#   maxWeight: 1000

# - name: MetalChest
#   code: EGSZ8363
#   maxHitPoints: 400
#   maxWeight: 2000

# - name: DirtPath
#   code: EGSZ8363
#   maxHitPoints: 20
#   flooring: true

# - name: FarmPlot
#   code: XHDK5308
#   maxHitPoints: 100
#   flooring: true

# - name: PumpkinPlant
#   code: JTUR9078
#   maxHitPoints: 100

# - name: PurpleFlower
#   code: OAQN7604
#   maxHitPoints: 20
#   ignoresProjectiles: true
#   flooring: true

# Structures

- name: ClayOven
  code: FDHS7551
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  craftingStationClass: Furnace
  clientConfig:
    displayNameId: Clay oven
    showDisplayNameOnHover: false
    animationSetName: clay-oven
    animationRepeats: true

- name: Workbench
  code: LLSV8391
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  craftingStationClass: Workbench
  clientConfig:
    displayNameId: Workbench
    showDisplayNameOnHover: false
    animationSetName: workbench
    animationFrameSequence: [1]

- name: Anvil
  code: ZXUS3914
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  craftingStationClass: Anvil
  clientConfig:
    displayNameId: Anvil
    showDisplayNameOnHover: false
    animationSetName: anvil
    animationFrameSequence: [1]

- name: Laboratory
  code: QGBL5850
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  craftingStationClass: Laboratory
  clientConfig:
    displayNameId: Laboratory
    showDisplayNameOnHover: false
    animationSetName: laboratory
    animationFrameSequence: [1]

- name: WoodenFence
  code: AOBB6092
  highBlocking: true
  baseMaxHitPoints: 50
  baseGloryValue: 5
  clientConfig:
    displayNameId: Wooden fence
    showDisplayNameOnHover: false
    animationSetName: wooden-fence
    animationFrameSequence: [1]

- name: BrickWall
  code: YXPK5024
  highBlocking: true
  baseMaxHitPoints: 200
  baseGloryValue: 5
  clientConfig:
    displayNameId: Brick wall
    showDisplayNameOnHover: false
    animationSetName: brick-wall
    animationFrameSequence: [1]

- name: WoodenDoor
  code: FEQV9326
  extends: Door
  highBlocking: true
  baseMaxHitPoints: 50
  baseGloryValue: 5
  clientConfig:
    extendsClassName: Door
    displayNameId: Wooden door
    showDisplayNameOnHover: false
    animationSetName: wooden-door
    animationFrameSequence: [1]