
- name: WoodenWall

- name: StoneWall
  # code: QMYX4544
  highBlocking: true
  baseMaxHitPoints: 200
  baseGloryValue: 5
  clientConfig:
    displayName: Stone wall
    animationSetName: stone-wall
    animationFrameSequence: [1]

- name: Trap

- name: Bandit
  baseMaxHitPoints: 50
  baseGloryValue: 30
  baseDefence: 30
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  dropList:
    - itemName: Fabric
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayName: Bandit
    animationSetName: bandit
    animationRepeats: true

- name: Bat
  baseMaxHitPoints: 50
  baseGloryValue: 15
  baseMoveRate: 500
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  craftingStationClass: Workbench
  dropList:
    - itemName: Redcap
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayName: Bat
    animationSetName: bat
    animationRepeats: true

- name: Snake
  baseMaxHitPoints: 40
  baseGloryValue: 20
  baseMoveRate: 400
  baseWanderRate: 10000
  baseAttackRange: 2
  viewRange: 8
  dropList:
    - itemName: Greencap
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayName: Snake
    animationSetName: snake
    animationRepeats: true

- name: FireElemental
  baseMaxHitPoints: 60
  baseGloryValue: 40
  baseMoveRate: 600
  baseWanderRate: 10000
  baseAttackRange: 3
  viewRange: 8
  craftingStationClass: Furnace
  dropList:
    - itemName: Greencap
      dropRate: 100
      quantity: 4
  clientConfig:
    extendsClassName: Mob
    displayName: Fire elemental
    animationSetName: fire-elemental
    animationRepeats: true

- name: PineTree
  highBlocking: true
  baseMaxHitPoints: 100
  baseGloryValue: 10
  dropList:
    - itemName: PineLogs
      dropRate: 100
      quantity: 4
  clientConfig:
    displayName: Pine tree
    animationSetName: pine-tree
    animationFrameSequence: [1]

- name: IronRocks
  highBlocking: true
  baseMaxHitPoints: 200
  baseGloryValue: 20
  dropList:
    - itemName: IronOre
      dropRate: 100
      quantity: 4
  clientConfig:
    displayName: Iron rocks
    animationSetName: iron-rocks
    animationFrameSequence: [1]

# - name: Anvil
#   code: ZEWT6029
#   maxHitPoints: 300

# - name: WoodenChest
#   code: DUZJ6112
#   maxHitPoints: 250
#   maxWeight: 1000

# - name: MetalChest
#   code: EGSZ8363
#   maxHitPoints: 400
#   maxWeight: 2000

# - name: DirtPath
#   code: EGSZ8363
#   maxHitPoints: 20
#   flooring: true

# - name: FarmPlot
#   code: XHDK5308
#   maxHitPoints: 100
#   flooring: true

# - name: PumpkinPlant
#   code: JTUR9078
#   maxHitPoints: 100

# - name: PurpleFlower
#   code: OAQN7604
#   maxHitPoints: 20
#   ignoresProjectiles: true
#   flooring: true
