
- name: WoodenWall

- name: StoneWall
  # code: QMYX4544
  baseMaxHitPoints: 10
  baseGloryValue: 5
  clientConfig:
    animationSetName: stone-wall
    animationFrameSequence: [1]

- name: Trap

- name: Bandit
  baseMaxHitPoints: 50
  baseGloryValue: 30
  baseDefence: 30
  baseMoveRate: 700
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  clientConfig:
    extendsClassName: Mob
    displayName: Bandit
    animationSetName: bandit
    animationRepeats: true

- name: Bat
  baseMaxHitPoints: 50
  baseGloryValue: 15
  baseMoveRate: 500
  baseWanderRate: 10000
  baseAttackRange: 1
  viewRange: 8
  clientConfig:
    extendsClassName: Mob
    displayName: Bat
    animationSetName: bat
    animationRepeats: true

- name: PineTree
  baseMaxHitPoints: 10
  baseGloryValue: 10
  clientConfig:
    animationSetName: pine-tree
    animationFrameSequence: [1]

- name: IronRocks
  baseMaxHitPoints: 10
  baseGloryValue: 20
  clientConfig:
    animationSetName: iron-rocks
    animationFrameSequence: [1]

# - name: Anvil
#   code: ZEWT6029
#   maxHitPoints: 300

# - name: WoodenChest
#   code: DUZJ6112
#   maxHitPoints: 250
#   maxWeight: 1000

# - name: MetalChest
#   code: EGSZ8363
#   maxHitPoints: 400
#   maxWeight: 2000

# - name: DirtPath
#   code: EGSZ8363
#   maxHitPoints: 20
#   flooring: true

# - name: FarmPlot
#   code: XHDK5308
#   maxHitPoints: 100
#   flooring: true

# - name: PumpkinPlant
#   code: JTUR9078
#   maxHitPoints: 100

# - name: PurpleFlower
#   code: OAQN7604
#   maxHitPoints: 20
#   ignoresProjectiles: true
#   flooring: true