# Weapons
WoodenWeapon: 1
MetalDagger: 1
MetalSword: 1
MetalHammer: 1
Staff: 1
Bow: 1
Arrow: 1

# Clothing
MetalArmour: 1
Cloak: 1
Robe: 1

# Tools
GatheringTool: 1
Sickle: 1

# Resources/ingredients.
GenericMaterial: 4
Logs: 4
Ore: 5
PotionIngredient: 4
Gem: 2
RelicGem: 8
Seed: 1

# Consumables
Potion: 6
Scroll: 4
