# The default for each mob type. Any omitted properties on each mob type should fall back to what is defined here instead.
- name: Default
  gloryValue: 5
  maxHitPoints: 100
  defence: 0
  viewRange: 0
  moveRate: 1000
  wanderRate: 10000
  targetSearchRate: 4000
  attackRate: 1500
  meleeDamageAmount: 0
  meleeDamageTypes:
    - Physical
  meleeDamageArmourPiercing: 0
  projectileAttackType: null
  faction: Citizens
  behaviour: Cowardly
  corpseType: null
  dropList: []

- name: ArenaMaster
  moveRate: 0
  wanderRate: 0

- name: DwarfWeaponMerchant
  moveRate: 0
  wanderRate: 0

- name: Innkeeper
  moveRate: 0
  wanderRate: 0

- name: MagicMerchant
  moveRate: 0
  wanderRate: 0

- name: MeleeMerchant
  moveRate: 0
  wanderRate: 0

- name: OmniMerchant
  moveRate: 0
  wanderRate: 0

- name: PriestMerchant
  moveRate: 0
  wanderRate: 0

- name: RangedMerchant
  moveRate: 0
  wanderRate: 0

- name: Ruler
  moveRate: 0
  wanderRate: 0

- name: ToolMerchant
  moveRate: 0
  wanderRate: 0

- name: TrainingDummy
  gloryValue: 5
  maxHitPoints: 50
  moveRate: 0
  wanderRate: 0
  attackRate: 0
  targetSearchRate: 0

- name: Citizen
  maxHitPoints: 70
  viewRange: 8
  moveRate: 850
  meleeDamageAmount: 5
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: Fabric
    - itemName: PineLogs
    - itemName: Redcap

- name: Knight
  gloryValue: 40
  defence: 60
  viewRange: 6
  moveRate: 850
  projectileAttackType: IronSword
  faction: CityGuards
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: Redcap
      rolls: 2
    - itemName: IronBar
      rolls: 2
    - itemName: DungiumBar
      dropRate: 10

- name: Commander
  gloryValue: 200
  maxHitPoints: 200
  defence: 40
  viewRange: 6
  moveRate: 600
  projectileAttackType: DungiumSword
  faction: CityGuards
  corpseType: Human
  dropList:
    - itemName: HeartOfTheMountain
      dropRate: 2
    - itemName: GloryOrb
      dropRate: 100
      rolls: 2
    - itemName: ExpOrbMelee
      dropRate: 100
      rolls: 2
    - itemName: Gem
      rolls: 2
    - itemName: DungiumBar
      rolls: 10

- name: Warrior
  gloryValue: 35
  defence: 40
  viewRange: 7
  moveRate: 700
  projectileAttackType: IronHammer
  faction: Barbarians
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: IronOre
    - itemName: IronBar
      rolls: 4
    - itemName: Redcap

- name: Berserker
  gloryValue: 60
  maxHitPoints: 150
  defence: 70
  viewRange: 7
  attackRate: 1000
  moveRate: 500
  projectileAttackType: AgoniteSword
  faction: Barbarians
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: AgoniteOre
    - itemName: AgoniteBar
      rolls: 2
    - itemName: Redcap

- name: Druid
  gloryValue: 30
  viewRange: 7
  defence: 20
  faction: Mages
  corpseType: Human
  projectileAttackType: Wind
  dropList:
    - itemName: Bones
    - itemName: Cotton
    - itemName: Fabric
    - itemName: Redcap
    - itemName: Bluecap
    - itemName: Gem
    - itemName: HealAreaSpellScroll
      dropRate: 5
    - itemName: CleanseSpellScroll
      dropRate: 5
    - itemName: TailwindSpellScroll
      dropRate: 10
    - itemName: IronSickle
      dropRate: 5

- name: Elder
  gloryValue: 100
  viewRange: 7
  maxHitPoints: 200
  defence: 20
  faction: Mages
  corpseType: Human
  projectileAttackType: SuperWind
  dropList:
    - itemName: EyeOfTheStorm
      dropRate: 2
    - itemName: SacredBranch
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 2
    - itemName: ExpOrbMagic
      dropRate: 100
    - itemName: ExpOrbPotionry
      dropRate: 100
    - itemName: Gem
      dropRate: 100
      rolls: 2
    - itemName: HealAreaSpellScroll
    - itemName: CleanseSpellScroll
    - itemName: WardSpellScroll
    - itemName: PacifySpellScroll
    - itemName: TailwindSpellScroll
      dropRate: 100
      rolls: 5
    - itemName: NoctisSickle

- name: Mage
  gloryValue: 50
  viewRange: 7
  defence: 20
  faction: Mages
  corpseType: Human
  projectileAttackType: Fireball
  dropList:
    - itemName: Bones
    - itemName: Cotton
    - itemName: Fabric
    - itemName: Bluecap
    - itemName: Gem
    - itemName: WardSpellScroll
      dropRate: 5
    - itemName: PacifySpellScroll
      dropRate: 5
    - itemName: TailwindSpellScroll
      dropRate: 10

- name: ArchMage
  gloryValue: 150
  viewRange: 7
  maxHitPoints: 200
  defence: 20
  faction: Mages
  corpseType: Human
  projectileAttackType: SuperFireball
  dropList:
    - itemName: EternalFlame
      dropRate: 2
    - itemName: AngelHair
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 2
    - itemName: ExpOrbMagic
      dropRate: 100
      rolls: 2
    - itemName: HealAreaSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: CleanseSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: WardSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: PacifySpellScroll
      dropRate: 100
      rolls: 2
    - itemName: TailwindSpellScroll
      dropRate: 100
      rolls: 4
    - itemName: Gem
      dropRate: 100
      rolls: 4

- name: Prisoner
  gloryValue: 10
  viewRange: 5
  moveRate: 700
  meleeDamageAmount: 7
  faction: Outlaws
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: Cotton
      rolls: 2
    - itemName: Fabric
    - itemName: IronOre
  
- name: Bandit
  gloryValue: 30
  defence: 30
  viewRange: 6
  moveRate: 700
  attackRate: 2000
  projectileAttackType: IronDagger
  faction: Outlaws
  corpseType: Human
  dropList:
    - itemName: Bones
    - itemName: Fabric
      rolls: 2
    - itemName: IronOre
      rolls: 2
    - itemName: IronArrows
    - itemName: Gem
    - itemName: TailwindSpellScroll
      dropRate: 10

- name: BanditLeader
  gloryValue: 100
  maxHitPoints: 250
  defence: 30
  viewRange: 6
  moveRate: 500
  projectileAttackType: DungiumDagger
  faction: Outlaws
  corpseType: Human
  dropList:
    - itemName: SacredBranch
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 2
    - itemName: ExpOrbMelee
      dropRate: 100
      rolls: 2
    - itemName: DungiumArrows
      dropRate: 100
      rolls: 4
    - itemName: DungiumBar
      rolls: 4
    - itemName: TailwindSpellScroll
      dropRate: 100
      rolls: 4
    - itemName: Gem
      dropRate: 100
      rolls: 2

- name: Assassin
  gloryValue: 60
  maxHitPoints: 150
  defence: 30
  viewRange: 6
  moveRate: 300
  attackRate: 1000
  projectileAttackType: NoctisDagger
  faction: Outlaws
  corpseType: Human
  dropList:
    - itemName: Fabric
      rolls: 2
    - itemName: NoctisOre
    - itemName: NoctisBar
    - itemName: Shuriken
    - itemName: Gem
    - itemName: TailwindSpellScroll
      dropRate: 10

- name: MasterAssassin
  gloryValue: 500
  maxHitPoints: 400
  defence: 30
  viewRange: 6
  moveRate: 250
  attackRate: 1000
  projectileAttackType: NoctisDagger
  faction: Outlaws
  corpseType: Human
  dropList:
    - itemName: PrimeMatter
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 3
    - itemName: ExpOrbMelee
      dropRate: 100
      rolls: 2
    - itemName: ExpOrbRanged
      dropRate: 100
      rolls: 2
    - itemName: Shuriken
      dropRate: 100
      rolls: 2
    - itemName: NoctisBar
      rolls: 6
    - itemName: Gem
      dropRate: 100
      rolls: 4
    - itemName: TailwindSpellScroll
      dropRate: 100
      rolls: 4

- name: Rat
  maxHitPoints: 20
  viewRange: 4
  moveRate: 600
  meleeDamageAmount: 5
  faction: HostileAnimals
  taskIdKilled: Rats
  dropList:
    - itemName: Bones

- name: Bat
  gloryValue: 10
  maxHitPoints: 20
  viewRange: 4
  moveRate: 500
  meleeDamageAmount: 5
  faction: HostileAnimals
  dropList:
    - itemName: Bones

- name: Hawk
  gloryValue: 20
  maxHitPoints: 40
  viewRange: 5
  moveRate: 500
  meleeDamageAmount: 8
  faction: HostileAnimals
  dropList:
    - itemName: Feathers
      dropRate: 100
    - itemName: Feathers
      dropRate: 50

- name: SandScamp
  gloryValue: 20
  viewRange: 5
  moveRate: 500
  attackRate: 2000
  meleeDamageAmount: 15
  faction: HostileAnimals
  dropList:
    - itemName: DungiumOre
    - itemName: Redcap

- name: GrassScamp
  gloryValue: 20
  viewRange: 5
  moveRate: 500
  attackRate: 2000
  meleeDamageAmount: 15
  faction: HostileAnimals
  dropList:
    - itemName: PineLogs
      rolls: 2
    - itemName: Greencap

- name: SnowScamp
  gloryValue: 35
  viewRange: 5
  moveRate: 600
  attackRate: 2500
  meleeDamageAmount: 20
  faction: HostileAnimals
  dropList:
    - itemName: AgoniteOre
    - itemName: Frostcap
      dropRate: 10

- name: GnarlPine
  gloryValue: 30
  defence: 60
  viewRange: 6
  moveRate: 0
  projectileAttackType: Acorn
  faction: HostileAnimals
  dropList:
    - itemName: PineLogs
      dropRate: 100
      rolls: 2
    - itemName: PineLogs
      rolls: 2

- name: GreatGnarl
  gloryValue: 300
  maxHitPoints: 300
  defence: 60
  viewRange: 6
  moveRate: 0
  projectileAttackType: Acorn
  faction: HostileAnimals
  dropList:
    - itemName: SacredBranch
      dropRate: 25
    - itemName: GloryOrb
      dropRate: 100
      rolls: 4
    - itemName: ExpOrbMelee
      dropRate: 100
    - itemName: ExpOrbRanged
      dropRate: 100
    - itemName: ExpOrbMagic
      dropRate: 100
    - itemName: ExpOrbGathering
      dropRate: 100
    - itemName: Gem
      dropRate: 100
      rolls: 6
    - itemName: OakLogs
      rolls: 8

- name: Goblin
  gloryValue: 20
  maxHitPoints: 80
  defence: 20
  viewRange: 5
  moveRate: 500
  attackRate: 2000
  projectileAttackType: IronDagger
  faction: Goblins
  dropList:
    - itemName: Bones
    - itemName: Cotton
    - itemName: Fabric
    - itemName: IronOre
    - itemName: Redcap
    - itemName: Greencap
    - itemName: IronArrows

- name: Snoovir
  gloryValue: 15
  viewRange: 6
  moveRate: 1200
  attackRate: 2000
  projectileAttackType: Snowball

- name: ZombieHuman
  gloryValue: 20
  viewRange: 4
  moveRate: 500
  meleeDamageAmount: 20
  faction: Zombies
  dropList:
    - itemName: Bones

- name: Mummy
  gloryValue: 40
  maxHitPoints: 150
  viewRange: 5
  moveRate: 1500
  attackRate: 2000
  meleeDamageAmount: 25
  faction: Zombies
  dropList:
    - itemName: Bones
    - itemName: PineLogs
    - itemName: Cotton
      rolls: 2
    - itemName: String
    - itemName: Fabric
    - itemName: Redcap

- name: CryptWarden
  gloryValue: 60
  maxHitPoints: 150
  defence: 40
  viewRange: 6
  moveRate: 1500
  attackRate: 2000
  projectileAttackType: DungiumSword
  faction: Zombies
  dropList:
    - itemName: Bones
    - itemName: IronBar
    - itemName: DungiumBar
      rolls: 2
    - itemName: Fabric
    - itemName: Gem

- name: Pharaoh
  gloryValue: 300
  maxHitPoints: 300
  defence: 30
  viewRange: 8
  attackRate: 800
  projectileAttackType: SuperFireball
  faction: Zombies
  dropList:
    - itemName: EternalFlame
      dropRate: 2
    - itemName: AngelHair
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 3
    - itemName: ExpOrbMagic
      dropRate: 100
      rolls: 2
    - itemName: ConsumeSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: EnthrallSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: DeathbindSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: ReanimateSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: Gem
      dropRate: 100
      rolls: 4
    - itemName: DungiumBar
      rolls: 4
    - itemName: OakLogs
      rolls: 4
  
- name: Vampire
  gloryValue: 50
  maxHitPoints: 150
  defence: 20
  viewRange: 6
  moveRate: 400
  attackRate: 1000
  meleeDamageAmount: 20
  meleeDamageTypes:
    - Physical
    - Biological
  meleeDamageArmourPiercing: 20
  faction: Vampires
  dropList:
    - itemName: Bones
    - itemName: Fabric
    - itemName: IronOre
    - itemName: VampireFang
    - itemName: Gem

- name: BloodPriest
  gloryValue: 60
  maxHitPoints: 150
  defence: 20
  viewRange: 7
  moveRate: 1200
  projectileAttackType: BloodBolt
  faction: Vampires
  dropList:
    - itemName: NoctisOre
    - itemName: Fabric
      rolls: 2
    - itemName: VampireFang
    - itemName: Gem
      rolls: 2

- name: BloodLord
  gloryValue: 300
  maxHitPoints: 400
  defence: 30
  viewRange: 6
  moveRate: 300
  attackRate: 1000
  meleeDamageAmount: 30
  faction: Vampires
  dropList:
    - itemName: PrimeMatter
      dropRate: 5
    - itemName: GloryOrb
      dropRate: 100
      rolls: 4
    - itemName: ExpOrbMelee
      dropRate: 100
    - itemName: ExpOrbMagic
      dropRate: 100
    - itemName: ConsumeSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: EnthrallSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: DeathbindSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: ReanimateSpellScroll
      dropRate: 100
      rolls: 2
    - itemName: Gem
      dropRate: 100
      rolls: 6
    - itemName: NoctisBar
      rolls: 8
    - itemName: VampireFang
      rolls: 3

- name: Dwarf
  viewRange: 7
  moveRate: 750
  meleeDamageAmount: 15
  dropList:
    - itemName: Bones
    - itemName: Fabric
    - itemName: Redcap
    - itemName: IronOre
    - itemName: IronBar
    - itemName: DungiumOre
    - itemName: IronPickaxe
      dropRate: 10

- name: DwarfWarrior
  gloryValue: 50
  viewRange: 7
  moveRate: 650
  defence: 50
  projectileAttackType: DungiumHammer
  dropList:
    - itemName: Bones
    - itemName: Redcap
    - itemName: IronOre
    - itemName: IronBar
    - itemName: DungiumOre
    - itemName: DungiumBar
      rolls: 3

- name: DwarfKnight
  gloryValue: 60
  defence: 40
  viewRange: 6
  moveRate: 650
  projectileAttackType: DungiumHammer
  faction: CityGuards
  dropList:
    - itemName: Bones
    - itemName: Redcap
      rolls: 2
    - itemName: Frostcap
    - itemName: DungiumBar
      rolls: 3

- name: IronGolem
  gloryValue: 70
  maxHitPoints: 200
  defence: 60
  viewRange: 6
  moveRate: 700
  attackRate: 3000
  meleeDamageAmount: 30
  faction: HostileAnimals
  dropList:
    - itemName: IronOre
      dropRate: 100
      rolls: 2
    - itemName: IronOre
      rolls: 4
    - itemName: Redcap
      dropRate: 10

- name: DungiumGolem
  gloryValue: 70
  maxHitPoints: 200
  defence: 80
  viewRange: 6
  moveRate: 700
  attackRate: 3000
  meleeDamageAmount: 40
  faction: HostileAnimals
  dropList:
    - itemName: DungiumOre
      dropRate: 100
      rolls: 2
    - itemName: DungiumOre
      rolls: 4
    - itemName: Redcap
      dropRate: 10

- name: AgoniteGolem
  gloryValue: 70
  maxHitPoints: 200
  defence: 100
  viewRange: 6
  moveRate: 700
  attackRate: 3000
  meleeDamageAmount: 50
  faction: HostileAnimals
  dropList:
    - itemName: AgoniteOre
      dropRate: 100
      rolls: 2
    - itemName: AgoniteOre
      rolls: 4
    - itemName: Redcap
      dropRate: 10

- name: NoctisGolem
  gloryValue: 70
  maxHitPoints: 200
  defence: 120
  viewRange: 6
  moveRate: 700
  attackRate: 3000
  meleeDamageAmount: 60
  faction: HostileAnimals
  dropList:
    - itemName: NoctisOre
      dropRate: 100
      rolls: 2
    - itemName: NoctisOre
      rolls: 4
    - itemName: Redcap
      dropRate: 10

- name: SmallAdumbral
  maxHitPoints: 50
  gloryValue: 50
  viewRange: 5
  moveRate: 300
  attackRate: 1000
  meleeDamageAmount: 10
  faction: HostileAnimals

- name: MediumAdumbral
  maxHitPoints: 150
  gloryValue: 100
  viewRange: 6
  moveRate: 400
  attackRate: 1500
  meleeDamageAmount: 20
  faction: HostileAnimals

- name: LargeAdumbral
  maxHitPoints: 300
  gloryValue: 200
  viewRange: 8
  moveRate: 500
  attackRate: 1000
  projectileAttackType: Dark
  faction: HostileAnimals
  dropList:
    - itemName: PrimeMatter
      dropRate: 5
    - itemName: GloryOrb
      rolls: 2