# Arrows

- name: IronArrow
  moveRate: 100
  range: 8
  damageAmount: 14
  damageTypes:
    - Physical
  damageArmourPiercing: 15
  textureFrames: iron-arrow

- name: DungiumArrow
  moveRate: 100
  range: 8
  damageAmount: 16
  damageTypes:
    - Physical
  damageArmourPiercing: 20
  textureFrames: dungium-arrow
  
- name: AgoniteArrow
  moveRate: 100
  range: 8
  damageAmount: 18
  damageTypes:
    - Physical
  damageArmourPiercing: 25
  textureFrames: agonite-arrow

- name: NoctisArrow
  moveRate: 100
  range: 8
  damageAmount: 20
  damageTypes:
    - Physical
  damageArmourPiercing: 30
  textureFrames: noctis-arrow

- name: ExplosiveArrow
  moveRate: 100
  range: 8
  textureFrames: explosive-arrow

- name: IceArrow
  moveRate: 100
  range: 8
  damageAmount: 8
  damageTypes:
    - Physical
    - Magical
  damageArmourPiercing: 30
  textureFrames: ice-arrow

- name: PoisonArrow
  moveRate: 100
  range: 8
  damageAmount: 5
  damageTypes:
    - Physical
    - Biological
  damageArmourPiercing: 50
  textureFrames: poison-arrow

- name: IllOmen
  moveRate: 100
  range: 8

# Shurikens

- name: Shuriken
  moveRate: 150
  range: 4
  damageAmount: 20
  damageTypes:
    - Physical
  textureFrames: shuriken
  spinDuration: 1000

# Daggers

- name: IronDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 8
  damageArmourPiercing: 50
  damageTypes:
    - Physical
  textureFrames: iron-dagger

- name: DungiumDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 9
  damageArmourPiercing: 50
  damageTypes:
    - Physical
  textureFrames: dungium-dagger

- name: AgoniteDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 10
  damageArmourPiercing: 50
  damageTypes:
    - Physical
  textureFrames: agonite-dagger

- name: NoctisDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 11
  damageArmourPiercing: 50
  damageTypes:
    - Physical
  textureFrames: noctis-dagger

# Swords

- name: IronSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 20
  damageTypes:
    - Physical
  textureFrames: iron-sword

- name: DungiumSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 24
  damageTypes:
    - Physical
  textureFrames: dungium-sword

- name: AgoniteSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 28
  damageTypes:
    - Physical
  textureFrames: agonite-sword

- name: NoctisSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 32
  damageTypes:
    - Physical
  textureFrames: noctis-sword

# Hammers

- name: IronHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 18
  damageTypes:
    - Physical
  textureFrames: iron-hammer

- name: DungiumHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 21
  damageTypes:
    - Physical
  textureFrames: dungium-hammer

- name: AgoniteHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 24
  damageTypes:
    - Physical
  textureFrames: agonite-hammer

- name: NoctisHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 27
  damageTypes:
    - Physical
  textureFrames: noctis-hammer

- name: HammerOfGlory
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 27
  damageTypes:
    - Physical
  textureFrames: hammer-of-glory
  scaleModifier: 1.2

# Hatchets

- name: BoneHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 6
  damageTypes:
    - Physical
  textureFrames: bone-hatchet
  spinDuration: 1000

- name: IronHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical
  textureFrames: iron-hatchet
  spinDuration: 1000

- name: DungiumHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical
  textureFrames: dungium-hatchet
  spinDuration: 1000

- name: AgoniteHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical
  textureFrames: agonite-hatchet
  spinDuration: 1000

- name: NoctisHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical
  textureFrames: noctis-hatchet
  spinDuration: 1000

# Pickaxes

- name: BonePickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 6
  damageTypes:
    - Physical
  textureFrames: bone-pickaxe
  spinDuration: 1000

- name: IronPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical
  textureFrames: iron-pickaxe
  spinDuration: 1000

- name: DungiumPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical
  textureFrames: dungium-pickaxe
  spinDuration: 1000

- name: AgonitePickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical
  textureFrames: agonite-pickaxe
  spinDuration: 1000

- name: NoctisPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical
  textureFrames: noctis-pickaxe
  spinDuration: 1000

# Sickles

- name: IronSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical
  textureFrames: iron-sickle
  spinDuration: 1000

- name: DungiumSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical
  textureFrames: dungium-sickle
  spinDuration: 1000

- name: AgoniteSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical
  textureFrames: agonite-sickle
  spinDuration: 1000

- name: NoctisSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical
  textureFrames: noctis-sickle
  spinDuration: 1000

# Magic

- name: Wind
  moveRate: 200
  range: 6
  damageAmount: 6
  damageTypes:
    - Magical

- name: SuperWind
  moveRate: 200
  range: 7
  damageAmount: 6
  damageTypes:
    - Magical

- name: Tailwind
  moveRate: 100
  range: 3
  damageAmount: 6
  damageTypes:
    - Magical

- name: Fireball
  moveRate: 200
  range: 6

- name: SuperFireball
  moveRate: 200
  range: 7

- name: BloodBolt
  moveRate: 200
  range: 6
  damageAmount: 20
  damageTypes:
    - Magical
    - Biological
  healAmount: 20

- name: SuperBloodBolt
  moveRate: 200
  range: 7
  damageAmount: 20
  damageTypes:
    - Magical
    - Biological
  healAmount: 20

- name: Deathbind
  moveRate: 200
  range: 6

- name: Pacify
  moveRate: 200
  range: 6

# Misc

- name: WoodenClub
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical
  textureFrames: wooden-club

- name: Acorn
  moveRate: 200
  range: 6
  damageAmount: 16
  damageTypes:
    - Physical
  textureFrames: acorn
  spinDuration: 1000
  scaleModifier: 0.6

- name: Snowball
  moveRate: 200
  range: 4
  damageAmount: 8
  damageTypes:
    - Physical
  textureFrames: snowball
  spinDuration: 1000

- name: IceShard
  moveRate: 200
  range: 6
  damageAmount: 14
  damageTypes:
    - Physical
    - Magical

- name: Dark
  moveRate: 100
  range: 7
  damageAmount: 20
  damageTypes:
    - Magical
  textureFrames: dark
  spinDuration: 1000

- name: VampireFang
  moveRate: 200
  range: 1
  collisionType: Melee
  damageAmount: 20
  damageTypes:
    - Physical
    - Biological
  textureFrames: vampire-fang
