name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign new tasks and bugs to backlog
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'code') ||
        contains(github.event.issue.labels.*.name, 'map') ||
        contains(github.event.issue.labels.*.name, 'audio') ||
        contains(github.event.issue.labels.*.name, 'visual') ||
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/Arcanorum/rogueworld/projects/1'
        column_name: 'Backlog'
